# -*- coding: utf-8 -*-
"""clustering_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DFVMFOfTomdnHtRYwQRgnNhtqeY4Hlx
"""

# ====================== clustering_utils.py ======================
import joblib
import numpy as np
import os
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==================== NOMBRES DE CLUSTERS ====================
cluster_names = {
    0: "Básicos con Déficit Tecnológico",
    1: "Intermedios con Fuerte Producto",
    2: "Intermedios Equilibrados",
    3: "Orientados al Cliente",
    4: "Iniciales / Estancados"
}

def train_and_save_clustering(pyme_info_list, n_clusters=5, model_path="MODELS/clustering_model.joblib"):
    """
    Entrena KMeans + Scaler y guarda el modelo.
    pyme_info_list: lista de diccionarios con 'niveles'
    """
    os.makedirs("MODELS", exist_ok=True)

    vectors = []
    for info in pyme_info_list:
        vec = [
            info['niveles']['Tecnologia'][0],
            info['niveles']['Producto'][0],
            info['niveles']['Cliente'][0]
        ]
        vectors.append(vec)

    vectors = np.array(vectors)

    scaler = StandardScaler()
    vectors_scaled = scaler.fit_transform(vectors)

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    kmeans.fit(vectors_scaled)

    model_dict = {
        'kmeans': kmeans,
        'scaler': scaler,
        'n_clusters': n_clusters
    }

    joblib.dump(model_dict, model_path)
    print(f"✅ Modelo de clustering guardado en: {model_path}")
    return model_dict


def load_clustering_model(model_path="MODELS/clustering_model.joblib"):
    """Carga el modelo guardado"""
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"No se encontró el modelo de clustering en {model_path}")

    model_dict = joblib.load(model_path)
    print("✅ Modelo de clustering cargado correctamente")
    return model_dict


def predict_cluster(niveles_dict, model_dict):
    """Predice el cluster de una PyME según sus 3 niveles"""
    vector = np.array([
        niveles_dict['Tecnologia'][0],
        niveles_dict['Producto'][0],
        niveles_dict['Cliente'][0]
    ]).reshape(1, -1)

    scaled = model_dict['scaler'].transform(vector)
    cluster_id = model_dict['kmeans'].predict(scaled)[0]

    return cluster_id, cluster_names.get(cluster_id, f"Cluster {cluster_id}")