# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlFBppGmIF9tzDs2T3gaEhTNVQYe9inP
"""

import os
import sys
import pandas as pd
from datetime import datetime

# Importar el predictor (ajusta la ruta si es necesario)
try:
    from rf_madurez import rf_predict
except ImportError:
    print("❌ No se encontró rf_madurez.py. Asegúrate de que esté en la misma carpeta.")
    sys.exit(1)

print("="*80)
print("   EVALUADOR DE MADUREZ INDUSTRIA 4.0 - PyMEs Ecuatorianas")
print("="*80)
print("Pipeline: Random Forest + ISM (Hoja de Ruta Personalizada)\n")

def main():
    print("¿Cómo deseas ingresar las respuestas?")
    print("1. Manualmente (responder 13 preguntas)")
    print("2. Desde archivo CSV (data/ejemplo_respuestas.csv)")
    opcion = input("\nElige una opción (1 o 2): ").strip()

    if opcion == "1":
        answers = obtener_respuestas_manual()
    elif opcion == "2":
        answers = obtener_respuestas_csv()
    else:
        print("Opción inválida. Usando modo manual.")
        answers = obtener_respuestas_manual()

    # Predicción con Random Forest
    print("\n🔄 Realizando predicción con Random Forest...")
    try:
        resultado = rf_predict(answers)

        print("\n" + "="*60)
        print("RESULTADOS DE MADUREZ")
        print("="*60)
        for dim, (nivel_num, nivel_texto) in resultado.items():
            print(f"• {dim:10}: Nivel {nivel_num} → {nivel_texto}")
        print("="*60)

        # Guardar resultado
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = "outputs"
        os.makedirs(output_dir, exist_ok=True)

        df_result = pd.DataFrame({
            "Dimension": list(resultado.keys()),
            "Nivel_Num": [v[0] for v in resultado.values()],
            "Nivel_Texto": [v[1] for v in resultado.values()]
        })
        df_result.to_csv(f"{output_dir}/resultado_{timestamp}.csv", index=False)
        print(f"\n✅ Resultado guardado en: {output_dir}/resultado_{timestamp}.csv")

    except Exception as e:
        print(f"❌ Error en la predicción: {e}")
        print("Verifica que el modelo esté en la carpeta 'models/' y que rf_madurez.py tenga la ruta correcta.")

    print("\n📋 Nota: La hoja de ruta completa con ISM se encuentra en el notebook 'Recomendacion.ipynb'")
    print("   Para una versión integrada completa, podemos ampliar este main.py más adelante.")

def obtener_respuestas_manual():
    print("\nIngresa las respuestas (valores del 1 al 4) para cada pregunta:")
    mapping = {
        'A.1.1': 'Puntaje_Dim1_Q1', 'A.1.2': 'Puntaje_Dim1_Q2', 'A.1.3': 'Puntaje_Dim1_Q3',
        'A.1.4': 'Puntaje_Dim1_Q4', 'A.2.1': 'Puntaje_Dim1_Q5', 'A.2.2': 'Puntaje_Dim1_Q6',
        'B.1.1': 'Puntaje_Dim2_Q1', 'B.1.2': 'Puntaje_Dim2_Q2', 'B.1.3': 'Puntaje_Dim2_Q3',
        'B.1.4': 'Puntaje_Dim2_Q4',
        'C.1.1': 'Puntaje_Dim3_Q1', 'C.1.2': 'Puntaje_Dim3_Q2', 'C.1.3': 'Puntaje_Dim3_Q3'
    }

    answers = {}
    for codigo in mapping.keys():
        while True:
            try:
                valor = int(input(f"  {codigo}: "))
                if 1 <= valor <= 4:
                    answers[codigo] = valor
                    break
                else:
                    print("   Ingresa un número entre 1 y 4.")
            except ValueError:
                print("   Ingresa un número válido.")
    return answers

def obtener_respuestas_csv():
    ruta = "data/ejemplo_respuestas.csv"
    if not os.path.exists(ruta):
        print(f"❌ No se encontró {ruta}. Creando ejemplo básico...")
        os.makedirs("data", exist_ok=True)
        ejemplo = pd.DataFrame([{
            'A.1.1':3,'A.1.2':2,'A.1.3':3,'A.1.4':2,'A.2.1':2,'A.2.2':3,
            'B.1.1':1,'B.1.2':2,'B.1.3':1,'B.1.4':1,
            'C.1.1':2,'C.1.2':3,'C.1.3':2
        }])
        ejemplo.to_csv(ruta, index=False)
        print("   Archivo de ejemplo creado.")

    df = pd.read_csv(ruta)
    # Tomamos la primera fila como ejemplo
    answers = df.iloc[0].to_dict()
    print(f"✅ Cargadas respuestas de ejemplo desde {ruta}")
    return answers

if __name__ == "__main__":
    main()